package jogoDaVelhaSocket.mensagem;

public enum TipoDeMensagem {

	JOGADA_INVALIDA,
	ESPERANDO_JOGADORES,
	CONECTAR_JOGADOR,
	ENVIANDO_JOGADA,
	JOGO_INICIADO,
	JOGADOR_FAZ_JOGADA,
	JOGADOR_ESPERA,
	JOGO_ENCERRADO_EMPATOU,
	JOGO_ENCERRADO_VENCEU,

}
